blank_issues_enabled: false

contact_links:
  - name: Support
    url: https://github.com/FlyInkTV/FlyInkStream-Engine/discussions/new?category=questions
    about: Ask the Fly Ink® community or support team for help

